### ISSUE TITLE
二等座余票数量疑似错误的反馈

### ISSUE THREAD

**Issue by lekai63** [elroy93/12306spy#2]
出发站：雁荡山
目标站：杭州东
验证日期：2024-02-26
车次：D3296

使用本程序查得：雁荡山-->余姚北 二等座余票6
![1](https://github.com/elroy93/12306spy/assets/8952695/91b9d60d-ecab-46ec-9053-b6e3116e7a41)

12306官方查得 二等座余票0
![2](https://github.com/elroy93/12306spy/assets/8952695/b512fc50-9dd3-4ede-9c3f-8171927e72c2)

**Comment by e1roy** [comment]
### 原因 
使用的是智行火车票的查询接口, 原接口可能有缓存. 
点击直达后, 如果购票页面依然是错误数据, 那么是接口缓存的问题. 

--- 
### 解决办法
刷新一下
