### ISSUE TITLE
【bug】查询错误: '广州东' is not in list

### ISSUE THREAD

**Issue by bryanchen463** [elroy93/12306spy#3]
查询深圳到天门点击链接直达报错
<img width="263" alt="image" src="https://github.com/elroy93/12306spy/assets/140571881/0d4bf27c-ad8e-45c5-b6bb-5a2289d97059">

**Comment by e1roy** [comment]
fixed 

原因
判断列车只使用了`开始时间`进行判断, 如果存在两个站点之间有同一个发车时间的两列车, 会出现这个问题. 

[fix commit](https://github.com/elroy93/12306spy/commit/9a05a3ffee9997a22a3e1c8618868e3e86a7647e)
