### ISSUE TITLE
安装完依赖后打不开

### ISSUE THREAD

**Issue by windy1021** [elroy93/12306spy#6]
<img src="https://s3.bmp.ovh/imgs/2024/03/25/0e71b55fdf3a0bd8.png"  />

**Comment by e1roy** [comment]
# 1  可能是端口被占用了, 关闭占用的端口号的进程 
检查端口是否被占用, 在cmd中执行 以下命令
```shell
netstat -ano | findstr :8081
```
查看端口占用的进程 , `[PID]`替换为上面的进程号
```shell
tasklist | findstr  [PID]
taskkill /PID [PID] /F 
```
---

# 2 更换端口号 
修改`install.bat`启动脚本中的 `8081`为其他随机端口
``` python
# 将端口修改成7777端口
python main.py --port 7777
```
